/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedLandRouteImport } from './routes/_authed/land'
import { Route as AuthedRecipientsRouteImport } from './routes/_authed/recipients'
import { Route as AuthedRecoveryKeyRouteImport } from './routes/_authed/recovery-key'
import { Route as AuthedVaultRouteImport } from './routes/_authed/vault'
import { Route as HandoverTokenRouteImport } from './routes/handover.$token'
import { Route as NotarizeTokenRouteImport } from './routes/notarize.$token'
import { Route as WitnessTokenRouteImport } from './routes/witness.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLandRoute = AuthedLandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipientsRoute = AuthedRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecoveryKeyRoute = AuthedRecoveryKeyRouteImport.update({
  id: '/recovery-key',
  path: '/recovery-key',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVaultRoute = AuthedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthedRoute,
} as any)
const HandoverTokenRoute = HandoverTokenRouteImport.update({
  id: '/handover/$token',
  path: '/handover/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NotarizeTokenRoute = NotarizeTokenRouteImport.update({
  id: '/notarize/$token',
  path: '/notarize/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WitnessTokenRoute = WitnessTokenRouteImport.update({
  id: '/witness/$token',
  path: '/witness/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/land': typeof AuthedLandRoute
  '/recipients': typeof AuthedRecipientsRoute
  '/recovery-key': typeof AuthedRecoveryKeyRoute
  '/vault': typeof AuthedVaultRoute
  '/handover/$token': typeof HandoverTokenRoute
  '/notarize/$token': typeof NotarizeTokenRoute
  '/witness/$token': typeof WitnessTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/land': typeof AuthedLandRoute
  '/recipients': typeof AuthedRecipientsRoute
  '/recovery-key': typeof AuthedRecoveryKeyRoute
  '/vault': typeof AuthedVaultRoute
  '/handover/$token': typeof HandoverTokenRoute
  '/notarize/$token': typeof NotarizeTokenRoute
  '/witness/$token': typeof WitnessTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/_authed/land': typeof AuthedLandRoute
  '/_authed/recipients': typeof AuthedRecipientsRoute
  '/_authed/recovery-key': typeof AuthedRecoveryKeyRoute
  '/_authed/vault': typeof AuthedVaultRoute
  '/handover/$token': typeof HandoverTokenRoute
  '/notarize/$token': typeof NotarizeTokenRoute
  '/witness/$token': typeof WitnessTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/land'
    | '/recipients'
    | '/recovery-key'
    | '/vault'
    | '/handover/$token'
    | '/notarize/$token'
    | '/witness/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/land'
    | '/recipients'
    | '/recovery-key'
    | '/vault'
    | '/handover/$token'
    | '/notarize/$token'
    | '/witness/$token'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/recover'
    | '/signup'
    | '/_authed/land'
    | '/_authed/recipients'
    | '/_authed/recovery-key'
    | '/_authed/vault'
    | '/handover/$token'
    | '/notarize/$token'
    | '/witness/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  HandoverTokenRoute: typeof HandoverTokenRoute
  NotarizeTokenRoute: typeof NotarizeTokenRoute
  WitnessTokenRoute: typeof WitnessTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/land': {
      id: '/_authed/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof AuthedLandRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipients': {
      id: '/_authed/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof AuthedRecipientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recovery-key': {
      id: '/_authed/recovery-key'
      path: '/recovery-key'
      fullPath: '/recovery-key'
      preLoaderRoute: typeof AuthedRecoveryKeyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vault': {
      id: '/_authed/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthedVaultRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/handover/$token': {
      id: '/handover/$token'
      path: '/handover/$token'
      fullPath: '/handover/$token'
      preLoaderRoute: typeof HandoverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notarize/$token': {
      id: '/notarize/$token'
      path: '/notarize/$token'
      fullPath: '/notarize/$token'
      preLoaderRoute: typeof NotarizeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/witness/$token': {
      id: '/witness/$token'
      path: '/witness/$token'
      fullPath: '/witness/$token'
      preLoaderRoute: typeof WitnessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedLandRoute: typeof AuthedLandRoute
  AuthedRecipientsRoute: typeof AuthedRecipientsRoute
  AuthedRecoveryKeyRoute: typeof AuthedRecoveryKeyRoute
  AuthedVaultRoute: typeof AuthedVaultRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLandRoute: AuthedLandRoute,
  AuthedRecipientsRoute: AuthedRecipientsRoute,
  AuthedRecoveryKeyRoute: AuthedRecoveryKeyRoute,
  AuthedVaultRoute: AuthedVaultRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  HandoverTokenRoute: HandoverTokenRoute,
  NotarizeTokenRoute: NotarizeTokenRoute,
  WitnessTokenRoute: WitnessTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
